<?php

/**
 * BaseValidation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $hash
 * @property integer $synonym_group_id
 * @property SynonymGroup $SynonymGroup
 * 
 * @method string       getHash()             Returns the current record's "hash" value
 * @method integer      getSynonymGroupId()   Returns the current record's "synonym_group_id" value
 * @method SynonymGroup getSynonymGroup()     Returns the current record's "SynonymGroup" value
 * @method Validation   setHash()             Sets the current record's "hash" value
 * @method Validation   setSynonymGroupId()   Sets the current record's "synonym_group_id" value
 * @method Validation   setSynonymGroup()     Sets the current record's "SynonymGroup" value
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseValidation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('validation');
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('synonym_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SynonymGroup', array(
             'local' => 'synonym_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}