<?php

/**
 * BaseSynonymGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property Doctrine_Collection $Word
 * @property Doctrine_Collection $WordSynonymGroup
 * @property Doctrine_Collection $Validation
 * 
 * @method string              getDescription()      Returns the current record's "description" value
 * @method Doctrine_Collection getWord()             Returns the current record's "Word" collection
 * @method Doctrine_Collection getWordSynonymGroup() Returns the current record's "WordSynonymGroup" collection
 * @method Doctrine_Collection getValidation()       Returns the current record's "Validation" collection
 * @method SynonymGroup        setDescription()      Sets the current record's "description" value
 * @method SynonymGroup        setWord()             Sets the current record's "Word" collection
 * @method SynonymGroup        setWordSynonymGroup() Sets the current record's "WordSynonymGroup" collection
 * @method SynonymGroup        setValidation()       Sets the current record's "Validation" collection
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSynonymGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('synonym_group');
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Word', array(
             'refClass' => 'WordSynonymGroup',
             'local' => 'synonym_group_id',
             'foreign' => 'word_id'));

        $this->hasMany('WordSynonymGroup', array(
             'local' => 'id',
             'foreign' => 'synonym_group_id'));

        $this->hasMany('Validation', array(
             'local' => 'id',
             'foreign' => 'synonym_group_id'));
    }
}