<?php

/**
 * BasePossibleWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $new_word
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $PossibleWordSynonymGroup
 * 
 * @method string              getNewWord()                  Returns the current record's "new_word" value
 * @method Doctrine_Collection getGroups()                   Returns the current record's "Groups" collection
 * @method Doctrine_Collection getPossibleWordSynonymGroup() Returns the current record's "PossibleWordSynonymGroup" collection
 * @method PossibleWord        setNewWord()                  Sets the current record's "new_word" value
 * @method PossibleWord        setGroups()                   Sets the current record's "Groups" collection
 * @method PossibleWord        setPossibleWordSynonymGroup() Sets the current record's "PossibleWordSynonymGroup" collection
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePossibleWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('possible_word');
        $this->hasColumn('new_word', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SynonymGroup as Groups', array(
             'refClass' => 'PossibleWordSynonymGroup',
             'local' => 'word_id',
             'foreign' => 'synonym_group_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('PossibleWordSynonymGroup', array(
             'local' => 'id',
             'foreign' => 'word_id'));
    }
}