<?php

/**
 * BasePossibleWordSynonymGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $word_id
 * @property integer $synonym_group_id
 * @property PossibleWord $PossibleWord
 * @property SynonymGroup $SynonymGroup
 * 
 * @method integer                  getWordId()           Returns the current record's "word_id" value
 * @method integer                  getSynonymGroupId()   Returns the current record's "synonym_group_id" value
 * @method PossibleWord             getPossibleWord()     Returns the current record's "PossibleWord" value
 * @method SynonymGroup             getSynonymGroup()     Returns the current record's "SynonymGroup" value
 * @method PossibleWordSynonymGroup setWordId()           Sets the current record's "word_id" value
 * @method PossibleWordSynonymGroup setSynonymGroupId()   Sets the current record's "synonym_group_id" value
 * @method PossibleWordSynonymGroup setPossibleWord()     Sets the current record's "PossibleWord" value
 * @method PossibleWordSynonymGroup setSynonymGroup()     Sets the current record's "SynonymGroup" value
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePossibleWordSynonymGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('possible_word_synonym_group');
        $this->hasColumn('word_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('synonym_group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PossibleWord', array(
             'local' => 'word_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('SynonymGroup', array(
             'local' => 'synonym_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}