<?php

/**
 * BaseFailWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $synonym_group_id
 * @property string $new_word
 * @property integer $count
 * @property SynonymGroup $SynonymGroup
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method integer      getSynonymGroupId()   Returns the current record's "synonym_group_id" value
 * @method string       getNewWord()          Returns the current record's "new_word" value
 * @method integer      getCount()            Returns the current record's "count" value
 * @method SynonymGroup getSynonymGroup()     Returns the current record's "SynonymGroup" value
 * @method FailWord     setId()               Sets the current record's "id" value
 * @method FailWord     setSynonymGroupId()   Sets the current record's "synonym_group_id" value
 * @method FailWord     setNewWord()          Sets the current record's "new_word" value
 * @method FailWord     setCount()            Sets the current record's "count" value
 * @method FailWord     setSynonymGroup()     Sets the current record's "SynonymGroup" value
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFailWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fail_word');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('synonym_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('new_word', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SynonymGroup', array(
             'local' => 'synonym_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}