<?php

/**
 * BaseWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $WordSynonymGroup
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getGroups()           Returns the current record's "Groups" collection
 * @method Doctrine_Collection getWordSynonymGroup() Returns the current record's "WordSynonymGroup" collection
 * @method Word                setName()             Sets the current record's "name" value
 * @method Word                setGroups()           Sets the current record's "Groups" collection
 * @method Word                setWordSynonymGroup() Sets the current record's "WordSynonymGroup" collection
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('word');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SynonymGroup as Groups', array(
             'refClass' => 'WordSynonymGroup',
             'local' => 'word_id',
             'foreign' => 'synonym_group_id'));

        $this->hasMany('WordSynonymGroup', array(
             'local' => 'id',
             'foreign' => 'word_id'));
    }
}