<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/03 17:11:27
sfConfig::add(array(
  'app_images_perWord' => 3,
  'app_images_width' => 60,
  'app_images_height' => 60,
  'app_images_filetype' => 'png',
));
