<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/22 23:45:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=captcha',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
