<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/04 17:03:24
sfConfig::add(array(
  'app_images_perWord' => 8,
  'app_images_width' => 60,
  'app_images_height' => 60,
  'app_images_filetype' => 'png',
));
