<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/03 16:34:21
sfConfig::add(array(
  'app_images_PerWord' => 64,
  'app_images_Width' => 60,
  'app_images_Height' => 60,
  'app_images_Filetype' => 'png',
));
