<?php

/**
 * FailWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FailWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FailWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FailWord');
    }
}