<?php

/**
 * PossibleWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PossibleWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PossibleWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PossibleWord');
    }
}