<?php

/**
 * SynonymGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SynonymGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SynonymGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SynonymGroup');
    }
}