<?php

/**
 * SynonymGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    captcha
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SynonymGroup extends BaseSynonymGroup
{
    static public function resizeImage($outFile, $inFile, $newWidth, $newHeight, $quality)
    {
        $src=imagecreatefromjpeg($inFile);
        $output=imagecreatetruecolor($newWidth, $newHeight);
        imagecopyresampled($output, $src, 0, 0, 0, 0, $newWidth, $newHeight, imagesx($src), imagesy($src));

        imagejpeg($output, $outFile, $quality);
        imagedestroy($src);
        imagedestroy($output);
    }
}
