<?php

/**
 * ValidationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValidationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValidationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Validation');
    }
}