<?php

/**
 * WordSynonymGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WordSynonymGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WordSynonymGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WordSynonymGroup');
    }
}